# -*- coding: utf-8 -*-
"""bowscratch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17bxHAVXLN4blqpTWvg8-9ye9mwdHyiNk
"""

import pandas as pd
import re
df = pd.read_csv('train-v2.tsv', sep='\t',header= None)
df

df.columns = ['class','tweet']

df

df['tweet'] = df['tweet'].str.replace('@USER','')

df

final_string=''
for i in df['tweet']:
  final_string+=i

final_string = re.sub(r'[0-9]+','',final_string)
final_string

final_string = re.sub('[^A-Za-z]+', ' ', final_string)
final_string

final_string = final_string.split()
final_string

from collections import Counter
a = dict(Counter(final_string))
a

sorted_a = sorted(a.items(), key=lambda kv: kv[1], reverse= True)

import collections

sorted_dict = collections.OrderedDict(sorted_a)
print(sorted_dict)

