# -*- coding: utf-8 -*-
"""p3 preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hcATt-75ZBrLiInv6E8ZQNPWw90yuCcy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import random

df = pd.read_csv('/content/train.tsv', sep='\t',header= None,encoding='utf8', quoting=3)

df.head()

df.columns = ['words','word_division']
df

df['word_division'] = df['word_division'].apply(lambda x: x.lower())

df['word_division'] = df['word_division'].apply(lambda x: x.split("-") )

df

def adding_chars(lenghts):
  temp=[]
  for i in lenghts:
    i=len(i)
    if i==1:
      temp.append("B")
    elif i==2:
      temp.append("B")
      temp.append("I")
    else:
      temp.append("B")
      temp.append("I")
      temp.append("I")
  return temp

def adding_tags(test):
  strings=adding_chars(test)
  return strings
print(adding_tags(['k', 'on', 's', 'i', 'l', 't', 'ank']))

df['word_tags'] = df['word_division'].apply(adding_tags)
df['word_tags']

df.head()

